os: linux
dist: bionic
language: python
python:
  - "3.7"

cache:
  pip: true
  ccache: true
  directories:
    - $HOME/.ccache
    - $HOME/.stack
    - $HOME/.conan

env:
  global:
    - MAKEFLAGS="-j2"

jobs:
  include:
    - stage: "Tests"
      name: "Python PEP8 checks"
      install:
        - pip install -r conf/requirements.txt
      script:
        - "make format"
        - "test $(git status --porcelain | wc -l) -eq 0 || { git diff; false; }"

    - name: "Generate report.hml"
      install:
        - sudo apt-get install gperf -y
        - sudo apt-get install libfl-dev -y
        - sudo apt-get install npm
        - sudo apt-get install gcc-8 -y
        - sudo apt-get install g++-8 -y
        - sudo apt-get install yosys -y
        - sudo apt-get install iverilog -y
        - sudo apt-get install verilator -y
        - sudo ln -sf /usr/bin/gcc-8 /usr/bin/gcc
        - sudo ln -sf /usr/bin/g++-8 /usr/bin/g++
        - sudo ln -sf /usr/bin/ccache /usr/local/bin/gcc
        - sudo ln -sf /usr/bin/ccache /usr/local/bin/g++
        - sudo ln -sf /usr/bin/ccache /usr/local/bin/gcc-8
        - sudo ln -sf /usr/bin/ccache /usr/local/bin/g++-8
        - pip install -r conf/requirements.txt
        - mkdir -p ~/.local/bin
        - export PATH=$HOME/.local/bin:$PATH
        - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
        - curl https://sh.rustup.rs -sSf | sh -s -- -y
        - sudo cp .travis/disco.list /etc/apt/sources.list.d/disco.list
        - sudo apt update
        - sudo apt install libantlr4-runtime-dev antlr4 -y
        - pip install virtualenv
        - pip install -r third_party/tools/hdlConvertor/requirements.txt
        - source $HOME/.cargo/env
      script:
        - "make slang"
        - "make odin"
        - "make zachjs-sv2v"
        - "make tree-sitter-verilog"
        - "make sv-parser"
        - "make hdlConvertor" 
        - "make generate-tests"
        - "make report USE_ALL_RUNNERS=1"
        - "touch out/report/.nojekyll"
      deploy:
        provider: pages
        github_token: $GH_TOKEN
        skip_cleanup: true
        keep_history: true
        local_dir: out/report
        verbose: true
        on:
          branch: master
